# -*- coding: utf-8 -*-
"""task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kj81wPKpu9hyL-17YrNIATDfGDHm6X6
"""

import pandas as pd
from google.colab import files

# Upload the file manually
uploaded = files.upload()

# Get the filename (first key in uploaded dict)
file_name = list(uploaded.keys())[0]

# Load the dataset
df = pd.read_csv(file_name)

# Display dataset info
print(df.info())
print(df.head())

#  1: Drop duplicate rows
df = df.drop_duplicates()

# 2: Handle missing values
# Example: Fill missing 'director' and 'cast' with 'Unknown'
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Not Rated')
df['duration'] = df['duration'].fillna('Unknown')

#  3: Convert and standardize date formats
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

#  4: Rename columns to lowercase and replace spaces with underscores
df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')

#  5: Standardize text data (example: type column)
df['type'] = df['type'].str.lower().str.strip()

#  6: Optional - Convert release_year to integer (already int64)
# Ensure duration and rating are string types
df['duration'] = df['duration'].astype(str)
df['rating'] = df['rating'].astype(str)

# Save the cleaned dataset
df.to_csv("cleaned_netflix_titles.csv", index=False)